applyToEachFace(..) - simplified each(..) for faces
CadQuery/cadquery-plugins pull request #20
Opened 2021-04-24 12:37 UTC by fedorkotov

This plugin simplifies using `Workplane.each(..)` on faces. To use each you have to select workplane coordinate system for each face before building your geometry. `Workplane.applyToEachFace()` function provided by this plugin separates tasks of choosing face coordinate system and actually building new geometry and provides a few built in ways of choosing coordinate system that 
are good enough in many cases.

See also https://github.com/CadQuery/cadquery/issues/713

2021-04-29 11:08 UTC, jmwright commented
@fedorkotov Is this ready for review?

2021-04-29 12:13 UTC, fedorkotov commented
@jmwright Yes, it is ready

2021-04-30 08:24 UTC, fedorkotov commented
Black found no issues but the action fails with
```
 Error: Error: Received status code 403
 Error: Error trying to create GitHub check for Black: Received status code 403
```

2021-04-30 18:03 UTC, jmwright reviewed
The apply-to-each-face submodule seems to be a dead end. If I try to update the submodules for your branch, git refuses to do it.

2021-04-30 19:03 UTC, fedorkotov commented
Sorry. Can't remember how and why did I add this `src/apply-to-each-face` thing.

2021-05-12 01:01 UTC, marcus7070 commented
I'll start my review today.

2021-05-12 03:17 UTC, marcus7070 requested changes
Aside from my comment about reloading the module, this all looks great to me!

2021-05-12 18:26 UTC, fedorkotov commented on plugins/apply_to_each_face/README.md
> +(see examples below). Otherwise second and subsequent runs will fail.
You are correct. I did not know about this CQ-Editor parameter. I modified README to include both variants (unchecking CQ-Editor parameter as a preferred option or reloading the module)

2021-05-12 21:20 UTC, marcus7070 approved these changes

2021-05-12 22:32 UTC, jmwright commented
@fedorkotov Thanks!

2021-05-12 22:32 UTC, merged